// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClaXDP4tQJpneqWHbn1vmgDL1QxIVFd98',
    appId: '1:1060878825457:web:2851d2573af3b491fd7650',
    messagingSenderId: '1060878825457',
    projectId: 'ecommerce-c6aa8',
    authDomain: 'ecommerce-c6aa8.firebaseapp.com',
    storageBucket: 'ecommerce-c6aa8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqOJD6EGuDfTSzpYuGu2ut7RpdapUaYXA',
    appId: '1:1060878825457:android:39678e642bbb8347fd7650',
    messagingSenderId: '1060878825457',
    projectId: 'ecommerce-c6aa8',
    storageBucket: 'ecommerce-c6aa8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALnuFmYYP94oJorWIb1VjX0sAhCtRDVhs',
    appId: '1:1060878825457:ios:eac3218d52e8a4c1fd7650',
    messagingSenderId: '1060878825457',
    projectId: 'ecommerce-c6aa8',
    storageBucket: 'ecommerce-c6aa8.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALnuFmYYP94oJorWIb1VjX0sAhCtRDVhs',
    appId: '1:1060878825457:ios:ea14c6a828c53999fd7650',
    messagingSenderId: '1060878825457',
    projectId: 'ecommerce-c6aa8',
    storageBucket: 'ecommerce-c6aa8.appspot.com',
    iosBundleId: 'com.example.ecommerceApp.RunnerTests',
  );
}
